name: Update Themes and Grammars

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-grammars:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: pnpm setup
        uses: pnpm/action-setup@v2

      - name: install
        run: pnpm install

      - run: pnpm run fetch
        env:
          GITHUB_TOKEN: ${{ secrets.FETCH_GITHUB_TOKEN }}

      - id: bump
        name: Bump versions
        run: pnpm run bump

      - uses: EndBug/add-and-commit@v9
        if: ${{ steps.bump.outputs.CHANGED == 'true' }}
        with:
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'feat: update Themes and Grammars [ci skip]'

      - run: pnpm -r publish
        if: ${{ steps.bump.outputs.CHANGED == 'true' }}
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
